数据类型：整型，浮点型，字符串型

整型

In [1]:
a=10

In [2]:
type(a)#判断数据类型

int

In [3]:
a=1000

In [4]:
a.bit_length()#内建方法，表示二进制字节数

10

In [5]:
a=10**100

In [6]:
a#python可以表示任意长度的整数

10000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

In [7]:
1+4

5

浮点型

In [11]:
b=0.35

In [12]:
b+0.1

0.44999999999999996

In [14]:
b.as_integer_ratio()##计算机在表示数的时候是不精确的，是二进制表达，且二进制位数有限，因此有误差
#相关误差在金融领域涉及到求和的时候，大量数字求和会放大误差

(3152519739159347, 9007199254740992)

In [15]:
#python的decimal模块给出了解决精度问题的方法
import decimal
from decimal import Decimal
decimal.getcontext()#参数表示精度、范围等参数

Context(prec=28, rounding=ROUND_HALF_EVEN, Emin=-999999, Emax=999999, capitals=1, clamp=0, flags=[], traps=[InvalidOperation, DivisionByZero, Overflow])

In [16]:
decimal.getcontext().prec=4#定义精度为4

In [17]:
e=Decimal(1)/Decimal(11)

In [18]:
e

Decimal('0.09091')

In [19]:
decimal.getcontext().prec=50

In [20]:
e=Decimal(1)/Decimal(11)

In [21]:
e

Decimal('0.090909090909090909090909090909090909090909090909091')

In [22]:
e+e

Decimal('0.18181818181818181818181818181818181818181818181818')

字符串型

In [26]:
t='this is a string object'

In [27]:
t.capitalize()#首字母大写

'This is a string object'

In [28]:
t.split()#分割

['this', 'is', 'a', 'string', 'object']

In [29]:
t.find('string')#从左往右（0-）包括空格第几个

10

In [31]:
t.find('Python')#找不到返回-1

-1

In [32]:
t.replace(' ','|')

'this|is|a|string|object'

In [36]:
t.replace(' ','|').split('|')

['this', 'is', 'a', 'string', 'object']

In [41]:
'http://www.python.org'.strip('htp:/')#strip去掉字符串中的某些字符，从左往右，一个字符可以代表连续的几个同样的字符

'ython.org'

In [42]:
import re#处理字符串的强大工具，regular expression,正则表达式

In [43]:
#re处理python的时间对象，将字符串处理成类似于datetime形式，再使用datetime对象
series="""
 '01/18/2018 13:00:00',100,'1st';
 '01/18/2018 13:30:00',110,'2nd';
 '01/18/2018 14:00:00',120.'3rd'
 """

In [44]:
series

"\n '01/18/2018 13:00:00',100,'1st';\n '01/18/2018 13:30:00',110,'2nd';\n '01/18/2018 14:00:00',120.'3rd'\n "

In [45]:
dt=re.compile("'[0-9/:\s]+'")#正则表达式的形式
result=dt.findall(series)

In [46]:
result

["'01/18/2018 13:00:00'", "'01/18/2018 13:30:00'", "'01/18/2018 14:00:00'"]

In [47]:
from datetime import datetime

In [49]:
pydt=datetime.strptime(result[0].replace("'",""),'%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2018, 1, 18, 13, 0)

数据结构：tuple,list,dict,set

tuple:小括号，index, count,一旦定义，不能轻易改变

In [50]:
t=(1,2.5,'data')

In [51]:
type(t)

tuple

In [52]:
t=1,2.5,'data'

In [54]:
type(t)

tuple

In [55]:
t[2]

'data'

In [56]:
t.count('data')

1

list:中括号，函数list可以用来定义和转化list对象，list可以改变，扩展，减少，切片

In [82]:
l=[1,2.5,'data']

In [83]:
l[1]

2.5

In [84]:
t

(1, 2.5, 'data')

In [85]:
list(t)

[1, 2.5, 'data']

In [86]:
l.append([4,3])#追加一个list

In [87]:
l

[1, 2.5, 'data', [4, 3]]

In [88]:
l.extend([1.0,1.5,2.0])#在list中增加数据量

In [89]:
l

[1, 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [90]:
l.insert(1,'insert')#在位置一上插入元素

In [91]:
l

[1, 'insert', 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [92]:
l.remove('data')


In [93]:
l

[1, 'insert', 2.5, [4, 3], 1.0, 1.5, 2.0]

In [97]:
p=l.pop(3)#把list中位置3的元素踢出来，放在p里，l只留下剩下来的

In [98]:
p

1.0

In [99]:
l

[1, 'insert', 2.5, 1.5, 2.0]

In [100]:
l[2:5]

[2.5, 1.5, 2.0]

In [102]:
for element in l[2:5]:
    print(element*2)

5.0
3.0
4.0


In [106]:
r=list(range(0,8,1))

In [107]:
r

[0, 1, 2, 3, 4, 5, 6, 7]

In [108]:
type(r)

list

In [109]:
for i in range(2,5):
    print(l[i]*2)

5.0
3.0
4.0


In [112]:
for i in range(1,10):
    if i%2==0: 
        print("%d is even" % i)
    elif i%3==0:
        print("%d is multiple of 3" % i)
    else:
        print("%d is odd" %i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


list comprehension的紧凑表达

In [114]:
m=[i**2 for i in range(5)]
m

[0, 1, 4, 9, 16]

函数编程

In [115]:
def f(x):
    return x**2

In [116]:
f(2)

4

In [122]:
def even(x):
    return x%2==0#判断，结果是布尔型true or false

In [125]:
print(list(map(even,range(10))))#map even函数到list的所有对象

[True, False, True, False, True, False, True, False, True, False]


In [126]:
print(list(map(lambda x:x**2,range(10))))#用lambda

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [128]:
print(list(filter(even,range(15))))#函数结果是布尔型，可以用来filter

[0, 2, 4, 6, 8, 10, 12, 14]


In [131]:
from functools import reduce
reduce(lambda x,y:x+y,range(10))#使用reduce可以将函数应用于list对象中的每一个元素，返回一个单一的值
#相当于cumsum

45

In [132]:
def cumsum(l):
    total=0
    for element in l:
        total+=element
    return total

In [133]:
cumsum(range(10))

45

dict字典型数据结构：大括号，key-value存储，list对象有序的并且可以排序，但是dict对象是无序的并且不可以排序

In [134]:
d={ 'Name':'Angela Merkel',
 'Country':'Germany',
 'Profession':'Chancelor',
 'Age':60 }

In [135]:
type(d)

dict

In [136]:
print(d['Name'],d['Age'])

Angela Merkel 60


In [137]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [138]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 60])

In [139]:
d.items()

dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])

In [140]:
birthday=True

In [142]:
if birthday is True:
    d['Age']+=1

In [144]:
print(d['Age'])

61


In [146]:
for item in d.items():#类似于list
    print(item)

('Name', 'Angela Merkel')
('Country', 'Germany')
('Profession', 'Chancelor')
('Age', 61)


In [147]:
for value in d.values():
    print(type(value))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'int'>


In [148]:
for key in d.keys():
    print(key)

Name
Country
Profession
Age


In [149]:
type(d.keys())#类似于list

dict_keys

set集合对象，大括号，无序，并且单个对象只能包含一次，交并补，对list对象去重

In [150]:
s=set(['u','d','ud','du','d','du'])

In [151]:
s

{'d', 'du', 'u', 'ud'}

In [153]:
list(s)#去重

['d', 'du', 'u', 'ud']

In [154]:
t=set(['d','dd','uu','u'])

In [155]:
s.union(t)

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [156]:
s.intersection(t)

{'d', 'u'}

In [158]:
s.difference(t)#在s中去掉t中有的成分

{'du', 'ud'}

In [159]:
t.difference(s)

{'dd', 'uu'}

In [160]:
s.symmetric_difference(t)#s去掉t和t去掉s,两者相加

{'dd', 'du', 'ud', 'uu'}

numpy
引入了对数组array的高效处理，n维array,ndarray类

使用python内建的数据结构构造array,通常用list
简单的list是一维数组，list中包含list,可以构建高维数组
list下标选择行，双重下标选择二维数组的元素，但是不好选择单列

In [161]:
v=[0.5,0.75,1.0,1.5,2.0]

In [162]:
m=[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [163]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [164]:
m[1][0]

0.5

In [165]:
v1=[0.5,1.5]
v2=[1,2]
m=[v1,v2]
c=[m,m]
c#多层嵌套的高维数组

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [166]:
c[1][1][0]

1

In [167]:
v=[0.5,0.75,1.0,1.5,2.0]
m=[v,v,v]
m    

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [168]:
v[0]='Python'

In [170]:
m#list可以通过索引改变，改变list之后，list构成的所有数组都要改变

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [171]:
from copy import deepcopy#使用deepcopy后，以后list的改变不会影响到已经形成的array
v=[0.5,0.75,1.0,1.5,2.0]
m=3*[deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [172]:
v[0]='python'
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

与使用list为基础处理数组不同，numpy.ndarray类明确的知道坐标轴，从矩阵中选择行或者列的方法具有一致性

In [173]:
import numpy as np

可以首先创建一个numpy.ndarray对象，然后再给它赋值。这里需要提供的参数如下：
* shape：可以是int，一组整数或者是对另一个numpy.ndarray的引用。
* dtype：（可选参数），是针对numpy.ndarray的Numpy具体数据类型。
* order：（可选参数），指明元素在内存中的存储顺序（C是C语言形式，行为标准，F是列为标准，Fortran语言形式）

In [174]:
a=np.array([0,0.5,1.0,1.5,2.0])
type(a)

numpy.ndarray

In [176]:
a[:2]#左闭右开区间

array([ 0. ,  0.5])

In [177]:
a.sum()

5.0

In [178]:
a.std()

0.70710678118654757

In [179]:
a.cumsum()

array([ 0. ,  0.5,  1.5,  3. ,  5. ])

In [180]:
a*2

array([ 0.,  1.,  2.,  3.,  4.])

In [181]:
a**2

array([ 0.  ,  0.25,  1.  ,  2.25,  4.  ])

In [182]:
np.sqrt(a)

array([ 0.        ,  0.70710678,  1.        ,  1.22474487,  1.41421356])

In [183]:
b=np.array([a,a*2])

In [184]:
b

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 0. ,  1. ,  2. ,  3. ,  4. ]])

In [185]:
b[0]

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [187]:
b[0,2]#第0行，第2列，行列等价

1.0

In [188]:
b.sum()

15.0

In [190]:
b.sum(axis=0)#每一列的和

array([ 0. ,  1.5,  3. ,  4.5,  6. ])

In [191]:
b.sum(axis=1)#每一行的和

array([  5.,  10.])

In [194]:
c=np.zeros((2,3,4),dtype='i',order='C')#shape是从最外面中括号往里数

In [195]:
c

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

ndarray类有两个特点，等长等宽等高，只有一种数据类型dtype

下面举例说明ndarray如何提升效率

In [198]:
import random
I=5000
%time mat=[[random.gauss(0,1) for j in range(I)] for i in range(I)]#使用list构造的过程

Wall time: 21.8 s


In [199]:
%time reduce(lambda x,y:x+y,[reduce(lambda x,y:x+y,row) for row in mat])#list cumsum

Wall time: 2.53 s


-419.6710775178849

In [200]:
%time mat=np.random.standard_normal((I,I))#numpy

Wall time: 1.35 s


In [201]:
%time mat.sum()

Wall time: 40.9 ms


-618.19876035247933

NumPy提供了结构数组允许每列中包含不同的NumPy数据类型。
* 结构数组的构造非常类似于SQL数据库，每一列都包含列名和列的数据类型，然后根据这个类型来赋值数据。
* 使用下标来访问数据。
* 结构数组的一个好处是每一列的单一元素可以是另外一个多维的对象而并不需要遵守基本的NumPy数据类型。

In [202]:
dt=np.dtype([('Name','S10'),('Age','i4'),('Height','f'),('Children/Pets','i4',2)])

In [203]:
s=np.array([('Smith',45,1.83,(0,1)),('Jones',53,1.72,(2,2))],dtype=dt)

In [204]:
s

array([(b'Smith', 45,  1.83000004, [0, 1]),
       (b'Jones', 53,  1.72000003, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [205]:
s['Name']

array([b'Smith', b'Jones'],
      dtype='|S10')

In [206]:
s['Height'].mean()

1.7750001

In [207]:
s[1]['Age']

53

In [210]:
r=np.random.standard_normal((4,3))
s=np.random.standard_normal((4,3))

In [212]:
r+s#NumPy提供了大量的向量化操作工具，例如：将两个数组元素一对一相加。

array([[ 1.34720928,  0.7104099 ,  1.59591457],
       [-1.86966472, -2.61949066,  0.79737763],
       [ 1.52095563,  0.47232208, -0.89175997],
       [-0.44330266, -1.61955077, -0.64847426]])

In [214]:
2*r+3#NumPy支持broadcasting，允许我们将不同形状的数据在一次操作中综合起来
#例如，当把一个标量加到一个向量的时候，标量就是被broadcasting的，然后与向量的每一个元素加起来。

array([[ 4.22398456,  4.41609291,  3.80294261],
       [-1.09880587,  0.42097414,  5.56500428],
       [ 3.89948413,  2.93541711,  3.14092648],
       [ 4.36130137, -0.63893737,  3.52776166]])

In [215]:
s=np.random.standard_normal(3)
r+s

array([[  2.83136318e+00,   2.22782332e+00,   1.91890288e-03],
       [  1.69967964e-01,   2.30263932e-01,   8.82949736e-01],
       [  2.66911296e+00,   1.48748542e+00,  -3.29089161e-01],
       [  2.90002158e+00,  -2.99691822e-01,  -1.35671572e-01]])

In [216]:
s=np.random.standard_normal(4)
r+s
#注意常常要与transpose函数配合使用。

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [217]:
r.transpose()+s

array([[ 0.36258553, -0.31348264,  0.14995235,  0.28869958],
       [ 0.4586397 ,  0.44640736, -0.33208116, -2.21141978],
       [ 0.15206455,  3.01842243, -0.22932648, -0.12807027]])

In [218]:
def f(x):
    return 3*x+5

In [219]:
f(r)

array([[ 6.83597684,  7.12413937,  6.20441391],
       [-1.1482088 ,  1.13146121,  8.84750641],
       [ 6.3492262 ,  4.90312567,  5.21138972],
       [ 7.04195205, -0.45840605,  5.79164249]])

* 作为一个一般的规则，用户定义的Python函数都可以用在numpy.ndarrays上，用法和基本数据类型是一致的。
* 这样可以避免纯Python代码的循环，而是将循环代理给numpy.ndarray以一种更高效的方式进行。这就是为什么使用Numpy的数组会提升效率的原因。

In [221]:
import math
math.sin(r)

TypeError: only length-1 arrays can be converted to Python scalars

注意标准Python的一些函数（例如sin）不能用于NumPy数组，而要使用NumPy提供的ufuncs，或者universal functions。

In [222]:
np.sin(r)

array([[ 0.57449929,  0.65035103,  0.39077308],
       [-0.8876375 , -0.96069997,  0.95873026],
       [ 0.43473326, -0.03228583,  0.07040495],
       [ 0.62929885, -0.96924003,  0.260829  ]])

In [223]:
np.sin(np.pi)

1.2246467991473532e-16

内存分配问题

In [224]:
x=np.random.standard_normal((5,10000000))#5行10000000列
y=2*x+3
C=np.array((x,y),order='C')
F=np.array((x,y),order='F')
x=0.0;y=0.0

In [227]:
C

array([[[ 1.68335473,  1.63123065,  0.42547794, ..., -0.65003885,
          0.85961901, -1.81384155],
        [ 0.49794258, -0.02544971,  0.87501605, ...,  0.37681516,
          0.5597533 , -1.15682957],
        [-0.64130461, -1.23799909, -0.89370538, ..., -0.0449132 ,
         -0.23473883, -0.86349743],
        [-0.17380771, -0.52576397,  0.30764201, ...,  0.63767395,
         -1.18060371, -0.1777034 ],
        [-1.97125219, -0.27029011,  0.63447114, ..., -1.65763852,
         -1.23054006,  0.6682229 ]],

       [[ 6.36670945,  6.2624613 ,  3.85095587, ...,  1.6999223 ,
          4.71923802, -0.62768309],
        [ 3.99588516,  2.94910058,  4.75003211, ...,  3.75363032,
          4.11950661,  0.68634087],
        [ 1.71739078,  0.52400183,  1.21258924, ...,  2.91017361,
          2.53052234,  1.27300514],
        [ 2.65238458,  1.94847206,  3.61528403, ...,  4.2753479 ,
          0.63879258,  2.6445932 ],
        [-0.94250438,  2.45941978,  4.26894228, ..., -0.31527705,
          0.53

In [226]:
C[:2].round(2)

array([[[ 1.68,  1.63,  0.43, ..., -0.65,  0.86, -1.81],
        [ 0.5 , -0.03,  0.88, ...,  0.38,  0.56, -1.16],
        [-0.64, -1.24, -0.89, ..., -0.04, -0.23, -0.86],
        [-0.17, -0.53,  0.31, ...,  0.64, -1.18, -0.18],
        [-1.97, -0.27,  0.63, ..., -1.66, -1.23,  0.67]],

       [[ 6.37,  6.26,  3.85, ...,  1.7 ,  4.72, -0.63],
        [ 4.  ,  2.95,  4.75, ...,  3.75,  4.12,  0.69],
        [ 1.72,  0.52,  1.21, ...,  2.91,  2.53,  1.27],
        [ 2.65,  1.95,  3.62, ...,  4.28,  0.64,  2.64],
        [-0.94,  2.46,  4.27, ..., -0.32,  0.54,  4.34]]])

In [228]:
%timeit C.sum()

125 ms ± 8.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [229]:
%timeit F.sum()

126 ms ± 2.97 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


当对数组元素进行求和的时候，在两种内存分配方案之间不存在什么效率的差别

In [230]:
%timeit C[0].sum(axis=0)#每一列的和

157 ms ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [231]:
 %timeit C[0].sum(axis=1)#每一行的和

66.5 ms ± 5.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


我们会看到加总五个向量得到一个单一的大向量要比加总10000000个小向量要慢,这是因为小向量中的单一元素，行，是依次存放的

In [232]:
%timeit F.sum(axis=0)

1.24 s ± 128 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [233]:
%timeit F.sum(axis=1)

2.39 s ± 208 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


当使用Fortran类型的存储的时候，相对的效率会发生较大的变化。这个时候较少大向量的加总会比较快